### ISSUE TITLE
Ways to connect VPN1 to the VPN2

### ISSUE THREAD

**Issue by AuthorShin** [AmCrypt0/VPN-Chaining#10]
ظاهرا ارتباط L2TP/IPsec و OpenVPN و حتی وایرگارد رو از حتی سرور های داخلی به خارجی محدود کردن.
راه دیگه ای برای اتصال این دو سرور به هم پیشنهاد نمیدید؟

**Comment by danaenayati** [comment]
سلام منم این مشکل رو دارم. راه حل دیگه ای وجود نداره؟

**Comment by AuthorShin** [comment]
@danaenayati 
سلام، یک راه ارتباطی از خودتون قرار بدید راهنماییتون میکنم.

**Comment by armantrd** [comment]
سلام موفق شدی؟ اگر تونستی به منم بگو.telgram:ar_trd
