### ISSUE TITLE
iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by appdroidbuilder** [AmCrypt0/VPN-Chaining#12]
iptables -t nat -D POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source ip
has problem

**Comment by thehxdev** [comment]
کلمه `public_iran_ip` در انتهای دستور رو با آیپی سرور ایران جایگزین کن

**Comment by derm400app** [comment]
سلام همون کارو کردم
 iptables -t nat -D POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source 195.28.xx.xxx

**Comment by derm400app** [comment]
اینم وایرگارد



interface: wg0
  public key: /zF5ot5doD6IDxxxxxxxx
  private key: (hidden)
  listening port: 80

peer: BcpylM+j16hwdYPCXxxxxxxxx
  preshared key: (hidden)
  endpoint: xxxxxxx:63468
  allowed ips: 10.7.0.2/32
  latest handshake:xxxxx
  transfer: 1.82 MiB received, 16.98 MiB sent

**Comment by thehxdev** [comment]
با همون اسکریپت که توی آموزشه وایرگارد نصب کردی؟

و اینکه دستور `ip a | grep wg` چه خروجی‌ای میده؟

**Comment by derm400app** [comment]
اره همون فقط پورت لسن وایرگارد رو عوض کردم به ۸۰

ip a | grep wg
4: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 10.7.0.1/24 scope global wg0

**Comment by thehxdev** [comment]
یبار دستور `systemctl enable --now wg-iptables.service` رو بزن و بعد دوباره دستور هارو تست کن

**Comment by derm400app** [comment]
@thehxdev 
ok shod
ولی خطا زیر داد


root@server:~# ip route add default via 10.8.0.2 table 120 
Error: Nexthop has invalid gateway.

**Comment by derm400app** [comment]
tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.120.20.14  netmask 255.255.254.0  destination 10.120.20.14
        inet6 fe80::e70f:298a:1381:4530  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 5  bytes 1385 (1.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 384 (384.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.7.0.1  netmask 255.255.255.0  destination 10.7.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 787  bytes 102948 (102.9 KB)
        RX errors 76  dropped 0  overruns 0  frame 76
        TX packets 46  bytes 1772 (1.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
