### ISSUE TITLE
Windows server

### ISSUE THREAD

**Issue by AuthorShin** [AmCrypt0/VPN-Chaining#9]
با سلام
آیا امکان ارائه اموزش برای استفاده از وبندوز سرور 2008 به عنوان VPN1 (سرور ایران) وجود دارد؟
با تشکر

**Comment by AuthorShin** [comment]
اگه لطف کنید برای L2TP/IPsec (هم ویندوز هم دبیان) رو هم توضیح بدید ممنون میشم. 

چون عملا در حال حاظر OpenVPN و Wireguard در اکثر سرویس دهنده ها محدود بوده و امکان اتصال به سرور ایران با این پروتکل ها مقدور نیستش.

**Comment by thehxdev** [comment]
با سرور ویندوز نمیشه VPN ساخت. حداقل تا اونجایی که من میدونم نمیشه.
وایرگارد هم اصلا پروتکل خوبی برای دور زدن فیلترینگ اونم توی شرایط حساس نیست چون به راحت مسدود میشه
الان بهترین پروتکل ها V2Ray و Xray و Shadowsocks هستن. (خصوصا دوتای اول)

**Comment by AuthorShin** [comment]
@thehxdev خوب الان دوتا سرور دبیان داریم یکی ایران یکی خارج ایران، چطوری باید با این روش هایی که گفتید کانفیگشون کرد؟

**Comment by AuthorShin** [comment]
ظاهرا میشه از داخل به سرور های ایران با L2TP/IPsec وصل شد و فقط الان مشکل وصل کردن سرور ایران به خارج هستش

**Comment by thehxdev** [comment]
https://t.me/wbnet/85199
